echo "Starting Debugging"

python debug_pose_annotation.py -i $1 -r "g1" -c "exoR"
python debug_pose_annotation.py -i $1 -r "g1" -c "exoL"
python debug_pose_annotation.py -i $1 -r "g1" -c "ego1R"
python debug_pose_annotation.py -i $1 -r "g1" -c "ego1L"
python debug_pose_annotation.py -i $1 -r "g1" -c "ego2L"
python debug_pose_annotation.py -i $1 -r "g1" -c "ego2R"
python debug_pose_annotation.py -i $1 -r "nao" -c "exoR"
python debug_pose_annotation.py -i $1 -r "nao" -c "exoL"
python debug_pose_annotation.py -i $1 -r "nao" -c "ego1R"
python debug_pose_annotation.py -i $1 -r "nao" -c "ego2R"
python debug_pose_annotation.py -i $1 -r "nao" -c "ego1L"
python debug_pose_annotation.py -i $1 -r "nao" -c "ego2L"
python debug_pose_annotation.py -i $1 -r "pepper" -c "exoR"
python debug_pose_annotation.py -i $1 -r "pepper" -c "exoL"
python debug_pose_annotation.py -i $1 -r "pepper" -c "ego1R"
python debug_pose_annotation.py -i $1 -r "pepper" -c "ego2R"
python debug_pose_annotation.py -i $1 -r "pepper" -c "ego1L"
python debug_pose_annotation.py -i $1 -r "pepper" -c "ego2L"
python debug_pose_annotation.py -i $1 -r "atlas" -c "exoR"
python debug_pose_annotation.py -i $1 -r "atlas" -c "exoL"
python debug_pose_annotation.py -i $1 -r "atlas" -c "ego1R"
python debug_pose_annotation.py -i $1 -r "atlas" -c "ego2R"
python debug_pose_annotation.py -i $1 -r "atlas" -c "ego1L"
python debug_pose_annotation.py -i $1 -r "atlas" -c "ego2L"
python debug_pose_annotation.py -i $1 -r "icub" -c "exoR"
python debug_pose_annotation.py -i $1 -r "icub" -c "exoL"
python debug_pose_annotation.py -i $1 -r "icub" -c "ego1R"
python debug_pose_annotation.py -i $1 -r "icub" -c "ego2R"
python debug_pose_annotation.py -i $1 -r "icub" -c "ego1L"
python debug_pose_annotation.py -i $1 -r "icub" -c "ego2L"

echo "Done"